//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJJA.Scoreboard.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color whiteScoreOn {
            get {
                return ((global::System.Drawing.Color)(this["whiteScoreOn"]));
            }
            set {
                this["whiteScoreOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color whiteScoreOff {
            get {
                return ((global::System.Drawing.Color)(this["whiteScoreOff"]));
            }
            set {
                this["whiteScoreOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color whiteScoreBg {
            get {
                return ((global::System.Drawing.Color)(this["whiteScoreBg"]));
            }
            set {
                this["whiteScoreBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color whiteAdvOn {
            get {
                return ((global::System.Drawing.Color)(this["whiteAdvOn"]));
            }
            set {
                this["whiteAdvOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 0")]
        public global::System.Drawing.Color whiteAdvOff {
            get {
                return ((global::System.Drawing.Color)(this["whiteAdvOff"]));
            }
            set {
                this["whiteAdvOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color whiteAdvBg {
            get {
                return ((global::System.Drawing.Color)(this["whiteAdvBg"]));
            }
            set {
                this["whiteAdvBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color whitePenOn {
            get {
                return ((global::System.Drawing.Color)(this["whitePenOn"]));
            }
            set {
                this["whitePenOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color whitePenOff {
            get {
                return ((global::System.Drawing.Color)(this["whitePenOff"]));
            }
            set {
                this["whitePenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color whitePenBg {
            get {
                return ((global::System.Drawing.Color)(this["whitePenBg"]));
            }
            set {
                this["whitePenBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color blueScoreOn {
            get {
                return ((global::System.Drawing.Color)(this["blueScoreOn"]));
            }
            set {
                this["blueScoreOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color blueScoreOff {
            get {
                return ((global::System.Drawing.Color)(this["blueScoreOff"]));
            }
            set {
                this["blueScoreOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color blueScoreBg {
            get {
                return ((global::System.Drawing.Color)(this["blueScoreBg"]));
            }
            set {
                this["blueScoreBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color blueAdvOn {
            get {
                return ((global::System.Drawing.Color)(this["blueAdvOn"]));
            }
            set {
                this["blueAdvOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50, 0")]
        public global::System.Drawing.Color blueAdvOff {
            get {
                return ((global::System.Drawing.Color)(this["blueAdvOff"]));
            }
            set {
                this["blueAdvOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color blueAdvBg {
            get {
                return ((global::System.Drawing.Color)(this["blueAdvBg"]));
            }
            set {
                this["blueAdvBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color bluePenOn {
            get {
                return ((global::System.Drawing.Color)(this["bluePenOn"]));
            }
            set {
                this["bluePenOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color bluePenOff {
            get {
                return ((global::System.Drawing.Color)(this["bluePenOff"]));
            }
            set {
                this["bluePenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bluePenBg {
            get {
                return ((global::System.Drawing.Color)(this["bluePenBg"]));
            }
            set {
                this["bluePenBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color timeOn {
            get {
                return ((global::System.Drawing.Color)(this["timeOn"]));
            }
            set {
                this["timeOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 50, 0")]
        public global::System.Drawing.Color timeOff {
            get {
                return ((global::System.Drawing.Color)(this["timeOff"]));
            }
            set {
                this["timeOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color timeBg {
            get {
                return ((global::System.Drawing.Color)(this["timeBg"]));
            }
            set {
                this["timeBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color luteOn {
            get {
                return ((global::System.Drawing.Color)(this["luteOn"]));
            }
            set {
                this["luteOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 50, 0")]
        public global::System.Drawing.Color luteOff {
            get {
                return ((global::System.Drawing.Color)(this["luteOff"]));
            }
            set {
                this["luteOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color luteBg {
            get {
                return ((global::System.Drawing.Color)(this["luteBg"]));
            }
            set {
                this["luteBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color whiteMedicalOn {
            get {
                return ((global::System.Drawing.Color)(this["whiteMedicalOn"]));
            }
            set {
                this["whiteMedicalOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color whiteMedicalOff {
            get {
                return ((global::System.Drawing.Color)(this["whiteMedicalOff"]));
            }
            set {
                this["whiteMedicalOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color whiteMedicalBg {
            get {
                return ((global::System.Drawing.Color)(this["whiteMedicalBg"]));
            }
            set {
                this["whiteMedicalBg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color blueMedicalOn {
            get {
                return ((global::System.Drawing.Color)(this["blueMedicalOn"]));
            }
            set {
                this["blueMedicalOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 0, 0")]
        public global::System.Drawing.Color blueMedicalOff {
            get {
                return ((global::System.Drawing.Color)(this["blueMedicalOff"]));
            }
            set {
                this["blueMedicalOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color blueMedicalBg {
            get {
                return ((global::System.Drawing.Color)(this["blueMedicalBg"]));
            }
            set {
                this["blueMedicalBg"] = value;
            }
        }
    }
}
